kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitops
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      restartPolicy: Always
      serviceAccountName: gitops
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        name: httpd
        image: httpd
        securityContext: {}
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8443
          name: https-port
        imagePullPolicy: IfNotPresent
